USE RECLAMACAO_DES;

INSERT INTO REGIAO (NOME) SELECT DISTINCT REGIAO FROM RECLAMACAO_DES ORDER BY 1 ASC;

INSERT INTO ESTADO (NOME, IDREGIAO)
  SELECT DISTINCT UF, IDREGIAO FROM RECLAMACAO_DES RD JOIN REGIAO R ON RD.REGIAO = R.NOME;

INSERT INTO CIDADE (NOME, IDESTADO)
  SELECT DISTINCT CIDADE, IDESTADO FROM RECLAMACAO_DES RD JOIN ESTADO E ON RD.UF = E.NOME;

INSERT INTO CONSUMIDOR (SEXO, FAIXAETARIA, IDCIDADE)
  SELECT DISTINCT SEXO, FAIXAETARIA, IDCIDADE FROM RECLAMACAO_DES RD JOIN CIDADE C ON RD.CIDADE = C.NOME;

INSERT INTO SEGMENTO (DESCRICAO) SELECT DISTINCT SEGMENTOMERCADO FROM RECLAMACAO_DES ORDER BY 1 ASC;

INSERT INTO AREA (DESCRICAO, IDSEGMENTO)
  SELECT DISTINCT AREA, IDSEGMENTO FROM RECLAMACAO_DES RD JOIN SEGMENTO S ON RD.SEGMENTOMERCADO = S.DESCRICAO;

-- REVER ESTA CONSULTA
INSERT INTO EMPRESA (NOMEFATASIA, IDAREA)
  SELECT DISTINCT NOMEFANTASIA, IDAREA FROM RECLAMACAO_DES RD JOIN AREA A ON RD.AREA = A.DESCRICAO;

INSERT INTO GRUPO (DESCRICAO) SELECT DISTINCT GRUPOPROBLEMA FROM RECLAMACAO_DES RD;

INSERT INTO PROBLEMA (DESCRICAO, IDGRUPO)
  SELECT DISTINCT PROBLEMA, IDGRUPO FROM RECLAMACAO_DES RD JOIN GRUPO G ON RD.GRUPOPROBLEMA = G.DESCRICAO;

INSERT INTO RECLAMACAO (IDCONSUMIDOR, ANO, MES, DATAABERTURA, DATARESPOSTA, DATAFINALIZACAO,
    TEMPORESPOSTA, IDEMPRESA, ASSUNTO, IDPROBLEMA, COMOCOMPROU, PROCUROUEMPRESA, RESPONDIDA,
    SITUACAO, AVALIACAO, NOTACONSUMIDOR)
    SELECT IDCONSUMIDOR, ANO, MES, DATAABERTURA, DATARESPOSTA, DATAFINALIZACAO,
    TEMPORESPOSTA, IDEMPRESA, ASSUNTO, IDPROBLEMA, COMOCOMPROU, PROCUROUEMPRESA, RESPONDIDA,
    SITUACAO, AVALIACAO, NOTACONSUMIDOR
      FROM RECLAMACAO_DES RD
        JOIN CIDADE C ON RD.CIDADE = C.DESCRICAO
        JOIN CONSUMIDOR CO ON RD.SEXO = CO.SEXO AND RD.FAIXAETARIA = CO.FAIXAETARIA
        JOIN EMPRESA E ON RD.NOMEFATASIA = E.NOMEFATASIA
        JOIN PROBLEMA P ON RD.PROBLEMA = P.DESCRICAO;

/* Possibilidade: Adicionar IDs fixos iguais a 0 e realizar UPDATE depois
 * UPDATE Avaliacao SET notaBrutaFG = NULL WHERE  notaBrutaFG = -1;
 */
